version: '3.5'

services:
  db:
    restart: always
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=vale
      - POSTGRES_PASSWORD=1234
    container_name: db_cryptobit
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - 5432:5432
