# Generated by Django 4.2.6 on 2023-10-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0002_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default='2023-10-21', verbose_name='Дата рождения'),
        ),
    ]
