# Generated by Django 4.2.6 on 2023-11-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftapi', '0003_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(default='2023-11-05', verbose_name='Дата рождения'),
        ),
    ]
